/* 틀렸음. 잘한다
SELECT B.PRODUCT_ID
     , B.PRODUCT_NAME
     , SUM(A.AMOUNT) * B.PRICE AS TOTAL_SALES
  FROM FOOD_ORDER A
 INNER JOIN FOOD_PRODUCT B
    ON A.PRODUCT_ID = B.PRODUCT_ID
 WHERE TO_CHAR(A.PRODUCE_DATE, 'MM') = '05'
 GROUP BY B.PRODUCT_ID, B.PRODUCT_NAME, B.PRICE
 */

/*
    *** FOOD_ORDER 의 월별 TOTAL_AMOUNT 구하기
 SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
   FROM FOOD_ORDER
  WHERE TO_CHAR(PRODUCE_DATE, 'MM') = '05'
  GROUP BY PRODUCT_ID
*/

/*
    *** 삽질 ***
SELECT A.PRODUCT_ID
     , A.PRODUCT_NAME
     , C.TOTAL_AMOUNT
  FROM FOOD_PRODUCT A
 INNER JOIN FOOD_ORDER B
    ON A.PRODUCT_ID = B.PRODUCT_ID
 RIGHT OUTER JOIN (
     SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
       FROM FOOD_ORDER
      -- WHERE TO_CHAR(PRODUCE_DATE, 'MM') = '05'
      GROUP BY PRODUCT_ID
 ) C
    ON A.PRODUCT_ID = C.PRODUCT_ID
 WHERE TO_CHAR(PRODUCE_DATE, 'MM') = '05'
   AND TO_CHAR(PRODUCE_DATE, 'YYYY') = '2022'
 GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME, C.TOTAL_AMOUNT
*/

-- 분노의 장고
-- SUM을 밖에서 하면 되는데 왜 삽질하나 할 일이 없나, WHERE도 묶어야할듯
SELECT A.PRODUCT_ID
     , A.PRODUCT_NAME
     , SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
  FROM FOOD_PRODUCT A
 INNER JOIN FOOD_ORDER B
    ON A.PRODUCT_ID = B.PRODUCT_ID
 WHERE TO_CHAR(PRODUCE_DATE, 'MM') = '05'
   AND TO_CHAR(PRODUCE_DATE, 'YYYY') = '2022'
 GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC