SELECT A.PRODUCT_ID
     , A.PRODUCT_NAME
     , (B.AMOUNT * A.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT A
         INNER JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
                     FROM FOOD_ORDER
                     WHERE TO_CHAR(PRODUCE_DATE,'YYYYMM') IN '202205'
                     GROUP BY PRODUCT_ID) B
                    ON (A.PRODUCT_ID = B.PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, B.PRODUCT_ID ASC