# 셀프조인 풀이(교집합)
SELECT DISTINCT C.CART_ID 
FROM CART_PRODUCTS C, CART_PRODUCTS T
WHERE C.CART_ID = T.CART_ID AND (C.NAME ='Milk' AND T.NAME ='Yogurt')
ORDER BY C.CART_ID

# Oracle INTERSECT 풀이
# SELECT CART_ID FROM CART_PRODUCTS
# WHERE NAME = 'Milk' 
# INTERSECT
# SELECT CART_ID FROM CART_PRODUCTS
# WHERE NAME = 'Yogurt'
# ORDER BY CART_ID

# 서브쿼리 사용 방식
# SELECT CART_ID FROM CART_PRODUCTS
# WHERE CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk')
# AND NAME = 'Yogurt'
# ORDER BY CART_ID ASC;